benches/hash.rs
src/circuit.rs
src/lib.rs
src/matrix.rs
src/mds.rs
src/poseidon.rs
src/preprocessing.rs
src/round_constants.rs

Optimize non-circuit performance by reducing multiplications from t^2 to 2t -1 per partial round, where t is the width.
- Compress constants by pushing them back through linear layers and through the identity components of partial layers.
- As a result, constants need only be added after each S-box.
- Having effectively moved the round-key additions into the S-boxes, refactor MDS matrices used for partial-round mix layer to use sparse matrices.
- This requires using a different (sparse) matrix at each partial round, rather than the same dense matrix at each.
- The MDS matrix, M, for each such round, starting from the last, is factored into two components, such that M' x M'' = M.
- M'' is sparse and replaces M for the round.
- The previous layer's M is then replaced by M x M' = M*.
- M* is …

Reduce multiplications

---

src/circuit.rs
src/matrix.rs
src/mds.rs
src/poseidon.rs

Since the sparse matrices used in partial rounds are exactly that (sparse), we don't need to use a full square matrix to represent them. Instead introduce `SparseMatrix` which, after checking, holds only the significant elements and omits the identity-matrix part.

Reduce memory

---

src/poseidon.rs

Some of the comments in `poseidon.rs` were leftovers from either the initial implementation or the long refactoring process on the way to current optimizations. This PR corrects at least some of that.

Bring comments up to date.

---

src/gpu.rs

```rust
#![feature(test)]
extern crate test;
#[derive(Debug, Clone, Copy)]
pub struct Fr([u64; 4]);
fn frs_2d_to_u64s(frs_2d: &[Vec<Fr>]) -> Vec<u64> {
frs_2d
.iter()
.flat_map(|row| frs_to_u64s(row).into_iter())
.collect()
}
fn frs_2d_to_u64s_fast(frs_2d: &[Vec<Fr>]) -> Vec<u64> {
let mut out: Vec<u64> = Vec::new();
for row in frs_2d.iter() {
for fr in row.iter() {
out.extend_from_slice(&fr.0);
}
}
out
}
fn frs_2d_to_u64s_fast2(frs_2d: &[Vec<Fr>]) -> Vec<u64> {
let len = frs_2d.iter().map(|row| row.len() * 4).sum();
let mut out: Vec<u64> = Vec::with_capacity(len);
for row in frs_2d.iter() {
for fr in row.iter() {
out.extend_from_slice(&fr.0);
}
}
out
}
#[bench]
fn bench_frs_2d_to_u64s(b: &mut test::Bencher) {
let data = vec![ vec![ Fr([0u64; 4]); 32 ]; 11];
b.iter(|| { …
```

fast frs_2d_to_u64s

---

Cargo.toml
gbench/Cargo.toml
src/batch_hasher.rs

Running bindgen at build time will burden all downstream users with an annoying dependency on clang, so use a new neptune-triton version which avoids this. This also means we need to avoid building the GPU code at all on MacOS. This PR is a bit of a hack, but it does allow running tests on MacOS with the gpu flag enabled. Actually using GPU on MacOS remains unsupported for now.

Use nepton-triton with no build-time bindgen.

---

Cargo.toml
gbench/Cargo.toml
gbench/src/bin/gbench.rs
src/batch_hasher.rs
src/gpu.rs
src/lib.rs
src/poseidon.rs

This PR fixes an observed GPU memory leak and preemptively addresses one not observed.
- Modify gbench to run multiple times to reproduce the observed leak: memory would increase on each run until OOM error.
- Address this problem by (allocating only a single lazy static `FutharkContext` and share it between `BatchHasher`s. This allows Futhark's memory management to function as designed.
- Modify gbench to pause after completion to observe whether memory returns to zero. It did not previously do so, which impinges on memory available for the next process to use the GPU.
- Address this problem by calling `futhark_context_clear_caches()` whenever a `BatchHasher` is dropped. This ensures all memory we have freed is released on the GPU.

fix GPU memory leak

---

gbench/src/bin/gbench.rs
src/batch_hasher.rs
src/column_tree_builder.rs
src/gpu.rs
src/lib.rs
src/tree_builder.rs

This PR adds support for `rows_to_discard`, which changes the general tree-building interface to return both the base row and the retained tree rows. The base row can be ignored by callers who don't need it because it was an input in the first place. In the case of the ColumnTreeBuilder, the base row is calculated and needs to be returned.
---
TODO:

Support rows_to_discard when building trees.

---

Cargo.toml
benches/hash.rs
benches/synthesis.rs
src/batch_hasher.rs
src/circuit.rs
src/gpu.rs
src/lib.rs
src/poseidon.rs

This PR ~makes strengthened Poseidon the default and~ adds GPU support for ~that variant~ strengthened Poseidon.
Since this work began, we have decided to revert to standard strength by default. That makes this branch name out of date, but I am leaving it in order to preserve the PR history.

improve support for strengthened poseidon

---

src/circuit.rs
src/lib.rs

The arity tag was previously being allocated in the circuit. It should be a constant, and because it is, we can compute the first round of constant additions and first quintic s-box over that value and use this constant result also. This saves 3 constraints per hash.

Make tag and first s-box using it constant.

---

src/lib.rs
src/poseidon-alt.rs
src/poseidon.rs
src/poseidon_alt.rs

This PR streamlines the primary hashing implementation by moving the `Correct` and `OptimizedDynamic` implementations to a new module, `poseidon_alt`. These code paths are valuable for ongoing validation that `OptimizedStatic` code path correctly implements its optimizations; and they provide some intermediate demonstration of the nature of those optimizations. They therefore retain value for validation, explanation, and as historical artifacts for understanding the code base. However, keeping them interspersed with the primary code path made that path harder to understand in isolation. Moving them to a new module serves both purposes.

Move 'correct' and 'dynamic' hashes to alt module.

---

src/column_tree_builder.rs
src/tree_builder.rs

The base layer was not actually being returned when building trees (code was commented out, probably for debugging). This PR fixes that and adds tests which would have caught it.

Actually return base layer when building trees.

---

Cargo.toml
gbench/Cargo.toml

This PR uses the latest neptune-trition (https://github.com/filecoin-project/neptune-triton/pull/8)  fixes the outdated gbench dependencies.

Update neptune-triton and pairing.

---

README.md
gbench/README.md
src/cl.rs

Usage:
`NEPTUNE_DEFAULT_GPU=<bus-id>`

feat: allow overwriting default gpu via env var

---

src/batch_hasher.rs
src/column_tree_builder.rs
src/error.rs
src/gpu.rs
src/lib.rs
src/tree_builder.rs

References to the OpenCl bindings cause downstream compile errors on macos.

Avoid compiling any OpenCl on macos.

---

gbench/src/bin/gbench.rs
src/lib.rs

`gbench` had gotten out of date and didn't compile. This PR fixes that.

Make GPUSelector accessible from gbench.

---

src/cl.rs

This PR mirrors #60 but applies the fix to the 1.2.x branch.

Get default device from NVIDIA platform, if any (v1.2.x)

---

src/cl.rs

GPU selection regressed by defaulting to the first platform return from `clGetPlatformIDs`, even though this is sometimes an unusable platform (like Clover — which appears on some systems but cannot run`neptune-triton`).
The short-term fix is to ensure that any available Nvidia platform is preferred as the default.

Get default device from NVIDIA platform, if any.

---

gbench/src/bin/gbench.rs
src/batch_hasher.rs
src/cl.rs
src/column_tree_builder.rs
src/gpu.rs
src/tree_builder.rs

Checking out a `FutharkContext` by `BusId` requires locking `FUTHARK_CONTEXT_MAP`. Since `ColumnTreeBuilder` requires two `BatchHashers`, each with a `FutharkContext`, creation was being interleaved such that if multiple were created in parallel (as in `gbench`), the first initiated was still blocked on initial context creation of the second.
This PR allows for explicit reuse of a single `FutharkContext`, avoiding this problem. It would be even better if context creation did not hold the Mutex — since it turns out that on some platforms (AMD…), this can be slow. However, the current fix addresses  the first immediate problem.

Explicitly reuse FutharkContext in related Batchers.

---

Cargo.toml
gbench/Cargo.toml
gbench/src/main.rs
src/batch_hasher.rs
src/cl.rs
src/column_tree_builder.rs
src/gpu.rs
src/tree_builder.rs

This PR depends on https://github.com/filecoin-project/rust-gpu-tools/pull/24, which moves the `GPUSelector` implementation into `rust-gpu-tools`. Once that PR merges, this one can be finalized (removing the Git dependency).

Refactor, moving device selection to rust-gpu-tools.

---

CHANGELOG.md

I wrongly released 2.3.0 before pulling the latest merged PRs. So I yanked that and will release this as 2.4.0.

Update changelog for 2.4.0

---

src/mds.rs

This just fixes a self-explanatory typo (`I` for `M`) in a comment's equation.

Fix comment equation.

---

.circleci/config.yml
CHANGELOG.md
Cargo.toml
README.md
gbench/Cargo.toml
gbench/src/main.rs
src/batch_hasher.rs
src/column_tree_builder.rs
src/error.rs
src/lib.rs
src/poseidon.rs
src/proteus/cl/poseidon.cl
src/proteus/gpu.rs
src/proteus/mod.rs
src/proteus/sources.rs
src/tree_builder.rs
src/triton/cl.rs
src/triton/gpu.rs
src/triton/mod.rs

This PR implements GPU batch hashing in pure OpenCL, implemented in the new `proteus` module. (Proteus and Triton are both moons of Neptune, hence the naming.)
This work is intended to introduce no change of behavior when the `gpu` feature flag is provided. If instead, the `opencl` feature flag is provided, a new `BatcherType`, `BatcherType::OpenCL` can be used instead of `BatcherType::GPU`. 
This implementation provides the following benefits when compared to the extant `neptune-triton` GPU implementation:
- Better perfomance (almost 2x, see below).
- Fewer external dependencies (removes dependence on elaborate Futhark code-generation and toolchain).
- Much less total code.
- Much lower GPU memory usage.
- No known problem with multiple batch hashers being used at once. (vs. an …

Implement pure OpenCL batch hashing.

---

CHANGELOG.md

When I released 2.5, it failed to publish to crates.io, and when I retried with `cargo release`, the minor version got bumped a second time. This PR updates the CHANGELOG to be in sync with the actual published version.

Update CHANGELOG for 2.6.

---

README.md

Adds a PDF version of the [Poseidon spec](https://github.com/filecoin-project/specs/pull/1252).

Poseidon spec

---

gbench/src/main.rs
src/batch_hasher.rs
src/column_tree_builder.rs
src/poseidon.rs
src/proteus/gpu.rs
src/tree_builder.rs
src/triton/gpu.rs

I went ahead with even more refactoring. The `BatcherType` looked like over-engineering to me. I like the code better without it.
The changes in rust-fil-proofs are quite minimal https://github.com/filecoin-project/rust-fil-proofs/compare/remove-batcher-type and will also be just as minimal for the scheduler work.
I thought if we are already doing breaking changes, we can also cleanup the API a bit.

Remove batcher type

---

.circleci/config.yml
Cargo.toml
gbench/src/main.rs
src/circuit.rs
src/mds.rs
src/poseidon.rs
src/round_constants.rs
src/round_numbers.rs
src/triton/gpu.rs

Clippy is run on CI, but even if there are warnings, the CI doesn't
fail. With this commit the CI fails when there are Clippy warnings.
It also runs Clippy on all the code (also benchmarks and examples)
now.

chore: improve Clippy on CI

---

.circleci/config.yml
Cargo.toml
README.md
gbench/Cargo.toml
gbench/src/main.rs
src/batch_hasher.rs
src/column_tree_builder.rs
src/error.rs
src/lib.rs
src/tree_builder.rs
src/triton/gpu.rs

Having a feature called "gpu" and one called "opencl" is confusing,
as both work with OpenCL. The difference is that the "gpu" feature
code path uses an OpenCL implementation that is written in Futhark.
To make this clearer, the "gpu" feature is renamed to "futhark".
This is my last change in my "cleanup the neptune codebase a bit" series. I'm not sure it is worth doing this change, but having a feature called "gpu" and one called "opencl" certainly confused me when I started to dig into the code. And as we are breaking APIs, we might as well change feature names now.

fix: rename gpu feature to futhark

---

src/proteus/gpu.rs

Don't push it into a GPU buffer piece wise, but at once from a pre-populated
vector. Running the benchmarking tool via
RUST_LOG=debug cargo run --release --no-default-features --features blst,opencl --package gbench
didn't indicate any performance difference on a Nvidia GeForce RTX 3090.
This is in preparation to make the code work with CUDA.

refactor: put everything into a vector first

---

src/proteus/gpu.rs

remove unnecessary `to_vec` to avoid one alloc and copy

remove unnecessary `to_vec`

---

src/proteus/sources.rs

Currently we use the master branch of `ec_gpu_gen`, which contains a
breaking change. You need to call `ec_gpu_gen::common()`, before any
other call.

fix: ec_gpu_gen::common() needs to be called

---

src/proteus/gpu.rs

In `rust-gpu-tools` v4.0.0 the definition of the global work size was
changed from the OpenCL to the CUDA definition. This means that the
global work size no longer needs to be a multiple of the local work
size, but it is the multiplier of the local work size. So the total
number of threads used is global work size * local work size.
I have no idea if a too higher number of grids (in CUDA lingo) causes any problems. Though this should certainly be fixed and should go out as a patch release.

fix: use correct global work size

---

src/proteus/cl/poseidon.cl

There is a warning about incompatible pointer types. Fix this by doing the
correct casting. This new cast makes it also work on CUDA, so we don't
need to special case this anymore.
The original warning was:
warning: incompatible pointer types passing '__constant Fr *' to parameter of type '__constant Fr (*)[3]' [-Wincompatible-pointer-types]

fix: fix warning when compiling with OpenCL

---

src/proteus/cl/poseidon.cl
src/proteus/gpu.rs

This is in preparation for supporting fields other than BLS12-381.
Make the field name part of all kernel functions.
Part of #130.

refactor: use field name as part of the function names

---

src/poseidon.rs

It makes sense semantically to specify `U1` in a downstream usage. In point of fact, it will be optimized away, but without U1 implementing Arity, there is no good way to signal this case generically.

Implement Arity for U1.

---

CHANGELOG.md
benches/synthesis.rs
src/circuit.rs
src/circuit2.rs
src/lib.rs

It came to my attention (cc: @BoyuanFeng) that our circuit uses more than the expected minimum number of constraints. I tracked this down to an extra constraint per round because we were converting linear combinations to allocated nums *before* applying the s-box — when in fact we can afford to wait until after.
With this fix applied, we now have 2 fewer than the 'expected' number. This is because we save 3 constraints by noting that the very first s-box applied to the constant domain tag has constant output. Then we have one extra constraint because we chose to allocate the final result.
This will be a breaking change to circuits, so we may need to provide backwards compatibility. I'm not 100% sure what the smoothest way to accomplish that will be, but this PR can be reviewed for …

Reduce constraints.

---

.circleci/config.yml
Cargo.toml
README.md
build.rs
gbench/Cargo.toml
gbench/src/main.rs
src/batch_hasher.rs
src/column_tree_builder.rs
src/lib.rs
src/poseidon.rs
src/proteus/cl/poseidon.cl
src/proteus/cl/shared.cl
src/proteus/gpu.rs
src/proteus/program.rs
src/proteus/sources.rs
src/tree_builder.rs

It is now possible to use Neptune with Pasta curves on the GPU. In
order to make that possible, two new compile-time features are introduced.
`bls` to use BLS12-381 and `pasta` to use the Pasta curves (Pallas and
Vesta).
BREAKING CHANGE: The API now requires to pass in the field that
should be used. It does no longer default to BLS12-381.
If the GPU is used (enabled by the `cuda` and/or `opencl` features), you
now also need to specify the supported fields, `bls` and/or `pasta`.

feat: support other fields

---

src/sponge/circuit.rs
src/sponge/vanilla.rs

The initial implementation of `SpongeCircuit::start()` used `make_elt` to construct the tag, and this resulted in an allocated num in the circuit. Really the tag should not be allocated. This all makes clear that the `SpongeTrait::make_elt` was an unnecessary and bad idea. This PR adds a test (which initially failed), modifies the implementation so the test passes, and adds a comment deprecating `SpongeTrait::make_elt`. I would have removed the method entirely, but I'd like to make a patch release with this fix so technically shouldn't alter the API.

Add sponge circuit synthesis test and remove make_elt method.

---

src/circuit2.rs
src/sponge/api.rs
src/sponge/circuit.rs
src/sponge/vanilla.rs

This PR changes the behavior of `SpongeAPI::absorb` to add the absorbed element to the state rather than replace the state element. This makes the `SpongeAPI` match the behavior of the `Sponge` trait and brings this implementation into agreement with the Sponge API Spec (which has been updated to specify this change).
I also added a test which makes explicit the number of permutations which should be expected for a range of absorb/squeeze patterns.
---
UPDATE: I have also added a fix to the circuit. The previous optimization to hard-code the capacity (DST) as constant (saving three constraints) is incorrect for sponges, where the capacity must be derived from the previous permutation.

Sponge absorb add

---

src/sponge/api.rs
src/sponge/circuit.rs
src/sponge/vanilla.rs

This PR renames `SpongeParameter::OpSequence` to `IOPattern` and enforces the specific pattern committed to at runtime. However, alternate equivalent patterns (after coalescing runs of absorb/squeeze ops) are still have the same tag so are compatible. This allows alternate implementations to enjoy runtime safety (checked against declared pattern) while still allowing freedom to chunk operations as desired. These changes bring the Sponge API implementation in sync with the spec (https://hackmd.io/bHgsH6mMStCVibM_wYvb2w) in its current state.

IO pattern

---

CHANGELOG.md

We will release these changes as 7.1.0. They include a bug-fix for the initial Sponge API implementation, and some small API changes to keep the neptune reference implementation in sync with the spec itself as that has been finalized.
The minor release is so Filecoin (which does not use the Sponge API) won't automatically pick up the release, even though it should be unaffected. Nova does use the Sponge API but needs this release (the bug fix in particular) before it can rely on the library.

Update CHANGELOG for 7.1.0.

---

CHANGELOG.md
src/sponge/api.rs
src/sponge/circuit.rs
src/sponge/vanilla.rs

This PR implements a quick fix to rename `InnerSpongeAPI::write_rate_element` to `add_rate_element` — making the implementation conform to the current spec. Hopefully this will be the last such minor fixup.

Rename write_rate_element to add_rate_element.

---

.circleci/config.yml

CircleCI stopped working with Xcode 12.5.1, hence upgrade
to the latest non-beta version 13.4.1.

chore: fix CI MacOS build

---

Cargo.toml
gbench/Cargo.toml
src/hash_type.rs
src/lib.rs
src/mds.rs
src/poseidon.rs
src/poseidon_alt.rs
src/serde_impl.rs

Manual serialization is needed for `PoseidonConstants` due to `Arity`'s `typenum` parameter, which doesn't have an easy serde implementation but is only used in `CType`. Serialization is thus skipped for `Arity` and easily calculable `PoseidonConstants` fields like `domain_tag` and `half_full_rounds`.
Once const generics are workable and https://github.com/filecoin-project/neptune/pull/125 is merged, we could instead derive serde automatically.

Implement serde for PoseidonConstants

---

src/circuit.rs
src/circuit2.rs

This PR changes the following:
* instead padding with a new allocated variable, we are using the "internal zero" of the linear combination, therefore simply a scalar coefficient.

Enforce zero

---

src/poseidon.rs

Type-level arithmetic avoids possible future macro input mistakes.

fix: Simplify the implementation of arity

---

.cargo/config
.github/workflows/rust.yml

This adds basic CI :
- running tests & doctests,
- compiling benchmarks,
- linting (rustfmt and clippy)
Until we figure out the CircleCI situation or setup a self-hosted GHA alternative.
Run on my fork [here](https://github.com/huitseeker/neptune/actions/runs/4536885726)

Add basic CI

---

.circleci/config.yml
src/halo2_circuit.rs
src/hash_type.rs
src/poseidon.rs

This PR adds documentation and code examples to Halo2 circuit-specific abstractions.
Also it enforces doc tests by CI, which aims to prevent documentation from becoming stale.
This PR targets `halo2` branch, but it additionally contains commits for covering `PoseidonConstants` and `Poseidon` abstractions with proper docs, so probably it will make sense to cherry-pick them to `master` branch.

Documenting Halo2 circuit-specific abstractions

---

.github/workflows/licenses-audits.yml
deny.toml

- Adds a new GitHub Action file for license audits
- Adds a new configuration file named 'deny.toml'
- Sets default values for options in the new configuration file (same as lurk-rs)

ci: Add licenses audits with 'cargo-deny'

---

Cargo.toml
benches/hash.rs
gbench/Cargo.toml
gbench/src/main.rs
src/circuit.rs
src/circuit2.rs
src/column_tree_builder.rs
src/hash_type.rs
src/lib.rs
src/matrix.rs
src/mds.rs
src/poseidon.rs
src/preprocessing.rs
src/proteus/gpu.rs
src/serde_impl.rs
src/sponge/circuit.rs
src/sponge/vanilla.rs
src/tree_builder.rs

~~Still testing this, in particular, the rust-gpu-tools import on the cuda / opencl features may have some issues.~~
Edit: solved by upgrading rust-gpu-tools to 0.7.1 in upstream `ec_gpu`.
Depends on https://github.com/filecoin-project/bellperson/pull/304
Fixes #171 
~~Edit(4/14): this needs work on the pasta-fil-curves repo.~~
Edit. (4/15): I'm seeing issues with tree builder tests hanging on opencl. Is this something you're seeing as well @porcuquine ?
**Historical (solved) issue:**
https://gist.github.com/huitseeker/230caa8cd63e049846f95ac0d8c77fe5
```
huitseeker@lightning.local➜~/tmp/neptune(bump_ff_group)» cargo tree -p rust-gpu-tools -i …
```

Bump ff & group to 0.13

---

release.toml

The default behaviour of cargo-release changed in v0.25. When there
is a workspace, it now consolidates all changes into a single commit
by default. This means that the commit message can't contain the
version number of a specific crate.
With adding a relase.toml file with the `consolidate-commits = false`
options restores the old behaviour and you get separate commits. We
release those two crates separately anyway.
I decided to use the release.toml file instead of putting it into
the Cargo.toml, to make it clearer that we use custom cargo-release
options. This can easily be overlooked if it's just a value in
the Cargo.toml.
Sister PR of https://github.com/filecoin-project/ec-gpu/pull/45

chore: make version part of the release commit

---

.github/workflows/licenses-audits.yml
.github/workflows/rust.yml

See https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue#triggering-merge-group-checks-with-github-actions

ci: trigger CI on PR add to a merge queue

---

.github/workflows/rust.yml

Closes #180 
The self-hosted runner uses this [Docker container](https://github.com/samuelburnham/hello-docker-action/blob/main/Dockerfile) (which can be upstreamed) as a [systemd service](https://github.com/samuelburnham/hello-docker-action/tree/main/server).
Future work:
- Move the `ocl-icd-opecl-dev` dependency to the Dockerfile
- Test with the `opencl` feature as well
- Upgrade the self-hosted hardware & potentially use it for other CI tests

Add self-hosted GPU CI

---

.github/workflows/rust.yml

- uses nextest for the GPU
- do not trigger CI on push (pushes on master occur through merge queue)

ci: tune triggers and use nextest in GPU

---

Cargo.toml
gbench/Cargo.toml

- Update dependencies to use `lurk-lab` fork's `dev` branch for `bellperson`, `ec-gpu`, `ec-gpu-gen`, and `pasta_curves`
- Modify `gbench` dependencies to align with main project upgrades

chore: Update dependencies to use lurk-lab dev branch

---

Cargo.toml
examples/poseidon_constants_serde.rs
src/hash_type.rs
src/lib.rs
src/mds.rs
src/poseidon.rs

This PR implements the `Abomonation` traits necessary for the upstream of faster public parameter caching in Nova. See https://github.com/lurk-lab/lurk-rs/pull/399 for details.
(This is also a copy-paste of https://github.com/winston-h-zhang/neptune/pull/1, moving the work there to a `lurk-lab` fork.)

Unsafe Serialization for Poseidon Constants

---

.github/workflows/upstream_update.yml

This adds an hourly job that checks every hour that the dev branch does sit on top of the latest main.
If that is not true, it will open an issue stating that, and assigning it to me. If the issue is open, it will update it with the latest info.
If that is true and an issue for this is still open, it will close the issue in question.

ci: Add action to signal when dev no longer incorporates changes 

---

Cargo.toml
gbench/Cargo.toml

See https://doc.rust-lang.org/cargo/reference/workspaces.html#the-dependencies-table

refactor: Bump rust-version to 1.64 and use workspace dependencies

---

.github/workflows/upstream_update.yml

This auto-rebases the dev branch in case the rebase is trivial, and keeps the former behavior (opening an issue) in case it is not.

ci: Implement rebase and test steps in upstream update workflow

---

src/sponge/vanilla.rs

- Deprecated `make_elt` function in `src/sponge/vanilla.rs` from version `0.10.0` onwards.

chore: Deprecate `make_elt` function in `vanilla.rs`

---

Cargo.toml
benches/synthesis.rs
src/circuit2.rs
src/circuit2_witness.rs
src/lib.rs
src/sponge/circuit.rs

This is nothing but a rebased and refreshed https://github.com/lurk-lab/neptune/pull/190 Please refer to the authoritative commit message there.
- Import and implement witness-generation for optimal Poseidon hash circuit into new file `circuit2_witness.rs` and update file `circuit2.rs` to accommodate these changes.
- Private methods in `circuit2.rs` are now public and deprecated function descriptions have been updated.
- The `BenchCircuit` struct in `synthesis.rs` has been refactored to include new functionalities and handle more cases.
- A module `circuit2_witness` is added to `lib.rs` for exclusively witness generation..
- The `bellpepper` dependency is moved from dev-dependencies to dependencies in `Cargo.toml` (due to using witness generation).
- Unit tests are introduced for the new …

feat: Integrate Poseidon hash witness generation into circuit2

---

.cargo/config
src/error.rs
src/lib.rs
src/poseidon_alt.rs
src/serde_impl.rs

- Introduce explicit anonymous lifetime specifiers to functions across multiple files, bumping us to rust-2018
- see https://doc.rust-lang.org/rustc/lints/listing/allowed-by-default.html#elided-lifetimes-in-paths
- make rust_2018_idioms a mandatory lint

refactor: Refactor to eliminate implied lifetimes across multiple files

---

.cargo/config
.gitignore
.vscode/settings.json
benches/hash.rs
src/error.rs
src/hash_type.rs
src/lib.rs
src/matrix.rs
src/mds.rs
src/poseidon.rs
src/proteus/gpu.rs
src/round_constants.rs
src/sponge/api.rs
src/sponge/vanilla.rs

Activates lints:
-Wunused_qualifications,
-Wclippy::cast_lossless,
Also cleans up:
-Wclippy::derive_partial_eq_without_eq

refactor: Set up a stricter xclippy

---

Cargo.toml
gbench/Cargo.toml

- Propagated a new `portable` feature across relevant crates and libraries, which toggles the same feature in blstrs,
- Updated the `Cargo.toml` for `blstrs` and `gbench` to include the new `portable` feature option.

chore: Propagate `portable` feature in cargo configurations

---

.cargo/config
Cargo.toml
benches/synthesis.rs
src/circuit.rs
src/circuit2.rs
src/circuit2_witness.rs
src/sponge/circuit.rs

- uses bellpepper 0.3.0,
- Replace `AllocatedNum::alloc` with `alloc_infallible`,
- remove the error management that becomes obsolete as a consequence, in private functions. 
No change to public APIs.

Ugrades before release

---

.github/workflows/rust.yml

- Avoids running CI on push to a local branch,
- Amends Github actions workflow to include `dev` branch in push and pull_request events,

ci: fix CI run conditions

---

src/circuit2_witness.rs
src/sponge/circuit.rs

Following up on this comment: https://github.com/lurk-lab/lurk-rs/pull/840#issuecomment-1791475246

use non-deprecated getters for WitnessCS

---

.cargo/config
gbench/src/main.rs
src/circuit.rs
src/circuit2.rs
src/column_tree_builder.rs
src/matrix.rs
src/mds.rs
src/poseidon.rs
src/poseidon_alt.rs
src/proteus/sources.rs
src/round_constants.rs
src/sponge/api.rs

- deprecates the duplicated, unused, subsumed`mul_pre_sum` in favor of `mul_sum`,
- deprecates an inefficient constructor for `SparseMatrix`,
- makes function visibility more clear & lints for `unreachable_pub` & `needless_pass_by_value`.

Neptune API maintenance

---

.github/workflows/check-downstream-compiles.yml

- Introduced a new GitHub Actions workflow "Build and Test Dependents", which is triggered on merge groups, pushes, and pull requests to `dev` branch.
- Enabled project consistency checks for `Arecibo` and `Lurk-rs` to ensure successful compilations.
This should help test PRs like #231

ci: Implement downstream compile checks for dev branch

---

.github/workflows/check-downstream-compiles.yml
Cargo.toml

While the computation of Neptune on the GPU is driven by the cuda and the opencl features, the bls/pasta features only drive the import of a modest amount of boilerplate code for ETL of GPU inputs and moduli in curve/field arithmetic:
- https://github.com/search?q=repo%3Afilecoin-project%2Fblstrs+%23%5Bcfg%28feature+%3D+%22gpu%22%29%5D&type=code
- https://github.com/search?q=repo%3Azcash%2Fpasta_curves+%23%5Bcfg%28feature+%3D+%22gpu%22%29%5D&type=code
This enables this code import by default, facilitating imports in upstream libraries, because feature propagation is then not needed. The cost is size in the linked binary.
- Enabled the "gpu" feature for "blstrs" and "pasta_curves" workspace dependencies by default in Cargo.toml file.

refactor: Simplify GPU features and dependencies in Cargo.toml

---

src/lib.rs
src/mds.rs
src/poseidon.rs
src/poseidon_alt.rs
src/preprocessing.rs

It's assumed a few places that the MDS matrix used in the mix step in neptune/poseidon is symmetric, but with just a few changes this doesn't have to be the case. This will allow neptune to be compatible with the [Poseidon reference implementation](https://extgit.iaik.tugraz.at/krypto/hadeshash).
Feel free to use these changes if you want, or perhaps just keep them for future reference.

suggestion: Allow non-symmetric MDS matrices

---

Cargo.toml

See :
- https://github.com/lurk-lab/arecibo/pull/277 and its integration into
- https://github.com/lurk-lab/arecibo/pull/279 (removing arecibo's pointer to blstrs, hence obsoleting the blstrs/ec-gpu forks)
- https://github.com/lurk-lab/arecibo/issues/332
> [!NOTE]
> The target of this PR is dev, not main, intentionally.

chore: remove no-longer-relevant forks on dev

---

Cargo.toml

Companion PR of https://github.com/lurk-lab/bellpepper/pull/84
> [!IMPORTANT]
> The CI failure on cargo-deny is expected (on commits pointing at the branch of the above PR).
> To stamp, please wait for the commit pointing the bellpepper dependency back to https://github.com/lurk-rs/bellpepper@dev

Switch bellpepper dependency

---

Cargo.toml

Fixes downstream `cargo-deny` errors

chore: Rename to argument

---

.github/workflows/rust.yml
Cargo.toml
deny.toml
rust-toolchain.toml
src/column_tree_builder.rs
src/error.rs
src/hash_type.rs
src/lib.rs
src/matrix.rs
src/mds.rs
src/poseidon.rs
src/poseidon_alt.rs
src/preprocessing.rs
src/round_constants.rs
src/round_numbers.rs
src/tree_builder.rs

This PR makes it `#[no_std]` compatible. 
It was tested in a [substrate](https://docs.substrate.io) pallet extrinsic and called in `polkadot.js.org` explorer:
```rust
pub fn test_neptune(origin: OriginFor<T>) -> DispatchResult {
let _caller = ensure_signed(origin)?;
let constants: PoseidonConstants<Fr, U8> = PoseidonConstants::new();
let mut preimage = [Fr::ZERO; 8];
preimage[0] = <Fr as Field>::ONE;
let mut h = Poseidon::<Fr, U8>::new_with_preimage(&preimage, &constants);
let _aa = h.hash();
Ok(())
}
```
I used `libm` to make the `ceil()` and friends available in `no_std` environments, not sure whether this is the right call for every env.

feat: make it #[no_std] compatible

---

.github/workflows/rust.yml

Switches to the [new GitHub-hosted GPU runners](https://github.blog/changelog/2024-07-08-github-actions-gpu-hosted-runners-are-now-generally-available/) for CI tests. This decreases maintenance overhead and cost.
The only drawback is that it requires installing CUDA on each run, which increases build time by a few minutes as the only available runner image is provided by Nvidia.
Successful run: https://github.com/argumentcomputer/neptune/actions/runs/12167602722

ci: Switch to GitHub-hosted GPU runner
