- Cargo.toml
Enables assembly optimizations for Fr mul_assign and add_assign. Gives around 10% perf boost on supported x86_64 systems
> feat: switch to fff

- Cargo.toml
- src/circuit.rs
Pending https://github.com/filecoin-project/bellman/pull/67, after which the Bellman version here needs to be updated. Meanwhile, this branch refers to the branch of that PR.
The work in this Bellman PR allows us to simplify code here and rely on Bellman: https://github.com/filecoin-project/bellman/pull/67
This PR makes those simplifications and updates to Bellperson 0.6.3.
> Move Bellman adaptations into Bellman.

- Cargo.toml
- src/column_tree_builder.rs
- src/lib.rs
- src/tree_builder.rs
This replaces #19 after rebasing the branch on `v1-0-candidate`.
> Add TreeBuilder (with no columns).

- Cargo.toml
- gbench/src/bin/gbench.rs
- src/batch_hasher.rs
- src/cl.rs
- src/column_tree_builder.rs
- src/error.rs
- src/gpu.rs
- src/lib.rs
- src/poseidon.rs
- src/tree_builder.rs
> feat: choose gpus

- gbench/src/bin/gbench.rs
- src/batch_hasher.rs
- src/cl.rs
- src/column_tree_builder.rs
- src/error.rs
- src/gpu.rs
- src/lib.rs
- src/tree_builder.rs
(This will break `rust-fil-nse-gpu` since `GPUSelector` has been moved from `neptune::cl::GPUSelector` to `neptune::GPUSelector`)
> fix: fix compilation on darwin

- .circleci/config.yml
- Cargo.toml
- src/error.rs
- src/gpu.rs
Use neptune-triton 2.0.0 for the reasons described in the PR which produced it: https://github.com/filecoin-project/neptune-triton/pull/20
> Use neptune-triton 2.0.0

- src/batch_hasher.rs
- src/cl.rs
- src/column_tree_builder.rs
- src/gpu.rs
- src/lib.rs
- src/tree_builder.rs
The fixes in #54 were on the 1.2.x branch. This PR applies them to the 2.x branch.
> Avoid compiling any OpenCl on macos.

- src/gpu.rs
The reason we call `futhark_context_clear_caches` is to free resources for some other kind of GPU job. We shouldn't do that until all currently active batch hashers have been dropped. To accomplish this, increment a counter (per `FutharkContext`) on creation and decrement on drop. When the counter hits zero, the last has been dropped, and it's safe to clear caches.
> Only clear cache when no hashers are active for futhark context.

- src/mds.rs
- src/poseidon.rs
This PR adds some explanation and corrects a test. Thanks to @saitima for asking questions.
> Clarify product order and correct test.

- src/proteus/gpu.rs
Macros are often used to reduce the boilerplate code to write. In case
of the kernel call the actual code isn't that much different from the
macro call.
A reader of the source code might suspect something complex going on in
the macro, although it's really straight forward. Hence I decided to
just replace the macro call with the actual code.
This also eases future uses of the call as type errors won't be hidden
within a macro, but will just be regular errors.
> refactor: replace macro call with function call

- .circleci/config.yml
- Cargo.toml
- README.md
- build.rs
- gbench/Cargo.toml
- gbench/src/main.rs
- src/batch_hasher.rs
- src/column_tree_builder.rs
- src/error.rs
- src/lib.rs
- src/proteus/cl/poseidon.cl
- src/proteus/cl/shared.cl
- src/proteus/gpu.rs
- src/proteus/mod.rs
- src/proteus/program.rs
- src/proteus/sources.rs
- src/round_numbers.rs
- src/tree_builder.rs
- src/triton/cl.rs
Neptune now also runs on CUDA. The OpenCL version is a bit slower than
previous versions, due to the removal of 64-bit limbs from the kernel.
Closed #104.
> feat: add support for CUDA

- Cargo.toml
- benches/synthesis.rs
- gbench/Cargo.toml
- src/circuit.rs
> refactor: remove pairing requirement for circuits

- Cargo.toml
- gbench/Cargo.toml
Requires https://github.com/filecoin-project/bellperson/pull/274 (and then a new release)
> feat: update dependencies to the latest

- README.md
> Add Sponge API to README.

- .circleci/config.yml
- src/hash_type.rs
- src/poseidon.rs
Cherry-picks the applicable changes from #170. All credit to @storojs72 for the actual work.
> Documentation

- .github/workflows/rust.yml
- Remove unecessary bits in CUDA testing
- Add a job for OpenCL testgin
- Enable all features during OpenCL testing
> ci: Improve testing for CUDA and OpenCL

- .github/workflows/rust.yml
- .vscode/settings.json
- Configure CUDA architecture using nvidia-smi probing
- Automatically set environment variables for CUDA compute and EC_GPU based on detected GPU architecture
> ci: Optimize compatibility for GPU jobs

- Cargo.toml
- gbench/Cargo.toml
FIxes issues encountered in #194
> Finalize using dev branches for our forks

- .github/workflows/rust.yml
- Introduce new GitHub workflow to handle Cargo MSRV checks
- merge clippy/rustfmt (this will need adjustment to branch protection settings)
> ci: add GitHub workflow check for Rust MSRV

- benches/synthesis.rs
- src/circuit2.rs
- src/circuit2_witness.rs
- src/lib.rs
- src/sponge/circuit.rs
This is precisely #190, rebased and squashed, without the (unneeded) Cargo.toml changes.
> [dev] Support optimized witness generation for circuit2.

- Cargo.toml
- benches/synthesis.rs
- gbench/Cargo.toml
- src/circuit.rs
- src/circuit2.rs
- src/sponge/circuit.rs
This branch is validating the approach in https://github.com/lurk-lab/bellpepper/pull/5
It’s a re-do of #215.
> Switch to bellpepper-core: v.2

- Cargo.toml
This aligns with bell{person, pepper}
> chore: Update `blake2s_simd` dependency version

- CODE_OF_CONDUCT.md
- Introduced a new `CODE_OF_CONDUCT.md` file to establish community standards and enforcement protocol
- from https://www.contributor-covenant.org/
> docs: Introduce code of conduct guidelines

- Cargo.toml
- README.md
- gbench/Cargo.toml
Maintain badges + update basic dependencies.
> Dependency maintenance

- .github/workflows/check-downstream-compiles.yml
- Cargo.toml
- src/circuit2_witness.rs
- src/sponge/circuit.rs
Update to bellpepper 0.4.0 and perform associated deprecation changes.
> Prepare release

- .github/workflows/rust.yml
- Cargo.toml
- examples/poseidon_constants_serde.rs
- src/hash_type.rs
- src/lib.rs
- src/mds.rs
- src/poseidon.rs
* abomonates poseidon constants
* under a feature "abomonation"
> Unsafe Serialization for Poseidon Constants

- src/poseidon.rs
> Fix poseidon.rs

- rust-toolchain.toml
> chore: update the rust toolchain (easy)
